apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer.fullname" . }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081 # TODO: change this
      protocol: TCP
      name: http
  selector:
    {{- include "explorer.selectorLabels" . | nindent 4 }}
